name: blev
description: A flutter plugin to communicate with Bluetooth Low Energy devices.
repository: https://github.com/viamrobotics/flutter-ble
version: 0.0.2
homepage: https://viam.com
topics:
  - bluetooth

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.25.2

flutter:
  plugin:
    platforms:
      android:
        package: com.viam.ble
        pluginClass: BlePlugin
      ios:
        pluginClass: BlePlugin
